// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obllonwzdjnokqeyvtsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibGxvbnd6ZGpub2txZXl2dHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODQzMjIsImV4cCI6MjA3MjU2MDMyMn0.4hxTc9zEL-GBG2k1pDBUjtQIQHWgYRgoPfOSQ6uOAJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});